Leads list service
FJala-Tr2020/back-end-e3 pull request #1
Opened 2021-07-06 14:07 UTC by vmkevv

[#53911](https://yourday.app/projects/c7a44e83-22e5-47cf-901e-29209beb4161/road-map?taskDetails=2727c097-0206-4783-a6fb-651648508dab) - Tarea

2021-07-07 22:27 UTC, marcelo-yourday requested changes

2021-07-13 15:08 UTC, vmkevv commented on src/models/Lead.ts
> +  country: string;
corregido

2021-07-13 15:08 UTC, vmkevv commented on src/models/Lead.ts
> +  createdAt: string;
Chaged to Date

2021-07-13 15:09 UTC, vmkevv commented on src/models/Lead.ts
> +    this.phone = '';
fixed

2021-07-13 15:09 UTC, vmkevv commented on src/handlers/leads.ts
> +    const rawText = await fileStore.readContent(fileNames.leads);
Created LeadsRepository class

2021-07-13 15:09 UTC, vmkevv commented on src/models/Lead.ts
> +export default class Lead {
filename changed

2021-07-13 15:14 UTC, vmkevv commented on src/index.ts
> +app.get('/leads', leadsHandler);
Yes, for every new resource we have, we need to add **just** one line of code, I think that is not a big deal. However I'm open to new suggestions.

2021-07-13 23:22 UTC, vmkevv commented on src/persistence/constants.ts
> +const storagePath = `${__dirname}/storage/`;
constants.ts deleted

2021-07-15 19:11 UTC, ElvisMiranda commented on src/index.ts
> +app.get('/leads', leadsHandler);
Hi @marcelo-yourday / @eencinasq. This file will certainly grow, what would be your advise in order to fix it and have this PR fixed/merged?

2021-07-19 13:34 UTC, eencinasq requested changes

2021-07-19 13:54 UTC, ElvisMiranda commented on src/index.ts
> +app.get('/leads', leadsHandler);
Oh, that's a great advice @eencinasq, let me work on that, thanks for sharing the link,

2021-07-22 03:35 UTC, vmkevv commented on src/index.ts
> +app.get('/leads', leadsHandler);
Leads router created

2021-07-22 23:56 UTC, eencinasq approved these changes

2021-07-22 23:57 UTC, merged